sudo: required
services:
  - docker

before_install:
  - docker build -t dockerdeployjatin/github-docker -f Dockerfile.dev . 

script:
  - docker run dockerdeployjatin/github-docker npm run test -- --coverage
  